steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build --build-arg GEMINI_API_KEY=$_GEMINI_API_KEY -t asia-southeast1-docker.pkg.dev/aisave4u/ai-apps-repo/www-app:latest .
images:
  - 'asia-southeast1-docker.pkg.dev/aisave4u/ai-apps-repo/www-app:latest'
